### ISSUE TITLE
Midori or WebKitGTK issue?

### ISSUE THREAD

**Issue by iamleot** [V1n1v131r4/MIME-Confusion-Attack-on-Midori-Browser#1]
Hello,
I have tried to reproduce that on Midori 0.5.11 (`midori-0.5.11nb26` in pkgsrc) on NetBSD/amd64 without any success (i.e. only the image is displayed and no `alert(...)` is showed).  This is with Midori 0.5.11 built against WebKitGTK 2.26.2.

Are you sure that's a Midori problem and not a more general WebKitGTK one?  Have you contacted Midori and/or WebKitGTK community about this problem?  Which WebKitGTK version is used?

**Comment by V1n1v131r4** [comment]
Hi iamleot!

I tested on Windows 10 and works fine for me. Try it.

**Comment by iamleot** [comment]
I do not have any Windows 10 machine and this doesn't cover any of my the previous questions.  It would be nice to have more details regarding this problem.  I think was probably a more general WebKitGTK problem (not specific to Midori) that was probably fixed in the last years.

**Comment by V1n1v131r4** [comment]
I answered that the test was done on Windows precisely because the version of Midori is different from the scenario you tested.  Even WebKit is different.  I reported the problem to the MITRE and when publishing CVE I reported to the midori project.
Going deeper, if you test with curl -I at the address you will see how the browser is informed about the content and how it handles it.  In the case of Midori on Windows 10, it receives HTTP response as Content-Type: application/javascript instead of Content-Type: image/jpeg

**Comment by iamleot** [comment]
OK, any idea which WebKitGTK version is used there?

**Comment by iamleot** [comment]
Can you please also share any public references regarding communication done with the Midori project too? (if any)

**Comment by V1n1v131r4** [comment]
I send email to the Astian Foundation (contact@astian.org).  
About WebKit on the project page does not speak the version, nor in Git.  In Windows environments WebKit comes with the browser package and does not run as system lib, as it is in Linux-like environments.

**Comment by iamleot** [comment]
If Midori provides a binary bundle, can you please ask them which WebKitGTK version was used so at least it can give possible interesting information for possible bisects?

Thanks!

**Comment by V1n1v131r4** [comment]
Hi iamleot!

I found some interesting information:
- Midori on Windows run on 0.5.x version however on Linux/BSD run in 7.x version (I tested on my Kali roling-release)
- On Windows, Midori 0.5.x doesn't run with WebKit. However on version 7.x it use WebKit

I think the problem is not webKit, in fact it seems to be the solution against the vulnerability I presented.

**Comment by iamleot** [comment]
Which web engine it used/uses on Windows? (version 0.5.x - at least on
Unix-like operating systems used WebKitGTK as well)

**Comment by V1n1v131r4** [comment]
They use Gecko on Windows.

**Comment by iamleot** [comment]
Allright then!  Thanks for investigating and clarifying that!

**Comment by V1n1v131r4** [comment]
You're welcome, my friend! 
Merry Christmas!

**Comment by iamleot** [comment]
Happy holidays to you too!
